"""empty message

Revision ID: 925f94e2acd6
Revises:
Create Date: 2021-01-23 21:09:25.068512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '925f94e2acd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impulse',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('power', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('impulse')
    # ### end Alembic commands ###
